modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="squakeport_1_20" #mandatory
version="1_03" #mandatory
displayName="Squake port 1.20/1.20.1" #mandatory
logoFile="squakeport.png" #optional
credits="Squeek502 for the original mod, Zeitheron for the ports up to 1.19.2"
authors="Pale Mannie, Manfred Blasser"
description='''
A Quake-style movement mod for Minecraft
'''
[[dependencies.squakeport_1_20]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.squakeport_1_20]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
